server:
    port: 8082
spring:
    cloud:
        gcp:
            project-id: ${PROJECT_ID}
            pubsub:
                emulator-host: ${EMULATOR_HOST}
    devtools:
        restart:
            enabled: true

feign:
    client:
        config:
            default:
                connectTimeout: 5000
                readTimeout: 5000
                loggerLevel: full

br:
    com:
        bullla:
            ploomes:
                url: ${BULLLA_PLOOMES_MS_URL}
                user-key: ${BULLLA_PLOOMES_MS_KEY}